### PR TITLE
Add fatiando stickers

### PR DESCRIPTION
**Pull request by santisoler**
Add new `stickers` folder with the svg and png files for a round sticker that includes `fatiando.org` text. Add a `stickers/README.md` with a table that showcase the available stickers in that folder.

### CODE REVIEW

**Comment by leouieda** [comment]
Nice! I'd add a bit more space between the text and borders/earth.

**Comment by santisoler** [comment]
Making the text smaller would work? something like this?

fatiando-logo-lower-left

**Comment by leouieda** [comment]
I'd make it smaller still. The logo should be the draw and the text is for people who were interested enough to read. Maybe make it a darker shade. Could use a very slightly blue gray tone for the text.

**Comment by leouieda** [comment]
That's what I did for the tshirt

**Comment by leouieda** [comment]
Looks great!

**Pull request merged**
